#!/bin/bash
VERILOG_VERSION="-g2012"
TESTBENCH_DIR="../testbenches"
DESIGN_DIR="../hdl_files/fwht"

TESTBENCH_SRC="L128_tb.sv"
DESIGN_SRC="LN.sv"
DESIGN_SRC2="L2.sv"

TESTBENCH_VVP="L128_tb.vvp"

iverilog $VERILOG_VERSION -o $TESTBENCH_VVP $DESIGN_DIR/$DESIGN_SRC $DESIGN_DIR/$DESIGN_SRC2 $TESTBENCH_DIR/$TESTBENCH_SRC
vvp $TESTBENCH_VVP
rm $TESTBENCH_VVP
