#!/bin/bash
VERILOG_VERSION="-g2012"
TESTBENCH_DIR="../testbenches"
DESIGN_DIR="../hdl_files/fwht"

TESTBENCH_SRC="L16_tb.sv"
DESIGN_SRC="L16.sv"
DESIGN_SRC2="L8.sv"
DESIGN_SRC3="L4.sv"
DESIGN_SRC4="L2.sv"

TESTBENCH_VVP="L16_tb.vvp"

iverilog $VERILOG_VERSION -o $TESTBENCH_VVP $DESIGN_DIR/$DESIGN_SRC $DESIGN_DIR/$DESIGN_SRC2 $DESIGN_DIR/$DESIGN_SRC3 $DESIGN_DIR/$DESIGN_SRC4 $TESTBENCH_DIR/$TESTBENCH_SRC
vvp $TESTBENCH_VVP