#!/bin/bash
VERILOG_VERSION="-g2012"
TESTBENCH_DIR="../testbenches"
DESIGN_DIR="../hdl_files/fwht"

TESTBENCH_SRC="L2_tb.sv"
DESIGN_SRC="L2.sv"
TESTBENCH_VVP="L2_tb.vvp"

iverilog $VERILOG_VERSION -o $TESTBENCH_VVP $DESIGN_DIR/$DESIGN_SRC $TESTBENCH_DIR/$TESTBENCH_SRC
vvp $TESTBENCH_VVP