#!/bin/bash
VERILOG_VERSION="-g2012"
TESTBENCH_DIR="../testbenches"
DESIGN_DIR="../hdl_files/fwht"

TESTBENCH_SRC="L64_tb.sv"
DESIGN_SRC="L64.sv"
DESIGN_SRC2="L32.sv"
DESIGN_SRC3="L16.sv"
DESIGN_SRC4="L8.sv"
DESIGN_SRC5="L4.sv"
DESIGN_SRC6="L2.sv"

TESTBENCH_VVP="L64_tb.vvp"

iverilog $VERILOG_VERSION -o $TESTBENCH_VVP $DESIGN_DIR/$DESIGN_SRC $DESIGN_DIR/$DESIGN_SRC2 $DESIGN_DIR/$DESIGN_SRC3 $DESIGN_DIR/$DESIGN_SRC4 $DESIGN_DIR/$DESIGN_SRC5 $DESIGN_DIR/$DESIGN_SRC6 $TESTBENCH_DIR/$TESTBENCH_SRC
vvp $TESTBENCH_VVP
rm $TESTBENCH_VVP