#!/bin/bash
VERILOG_VERSION="-g2012"
TESTBENCH_DIR="../testbenches"
DESIGN_DIR="../hdl_files/fwht"

TESTBENCH_SRC="L8_tb.sv"
DESIGN_SRC="L8.sv"
DESIGN_SRC2="L4.sv"
DESIGN_SRC3="L2.sv"

TESTBENCH_VVP="L8_tb.vvp"

iverilog $VERILOG_VERSION -o $TESTBENCH_VVP $DESIGN_DIR/$DESIGN_SRC $DESIGN_DIR/$DESIGN_SRC2 $DESIGN_DIR/$DESIGN_SRC3 $TESTBENCH_DIR/$TESTBENCH_SRC
vvp $TESTBENCH_VVP
rm $TESTBENCH_VVP